ecs-service-generic:
  env: preprod
  clusterName: preprod
  serviceName: &serviceName my-amazing-service
  replicas: 1
  memory: "512"
  cpu: "256"
  containerDefinitions:
    image: "tenant1/my-amazing-service:v1.0"
    name: *serviceName
    cpu: 0
    logConfiguration:
      options:
        awslogs-group: tenant1-preprod
    portMappings: 
    - containerPort: 8080
      hostPort: 8080
      protocol: tcp
    essential: true
    command:
    - "/opt/java/openjdk/bin/java"
    - "-jar"
    - "/jar/my-amazing-service.jar"
    secrets: 
      - name: "SECRET_CONNECTION"
        valueFrom: ""   # ADDED BY USER
    environment:
      - name: "STAGE"
        value: "preprod"
      - name: "TENANT"
        value: "tenant1"
  secrets:
   - arn:aws:secretsmanager:eu-west-1:*:secret:my-amazing-service-??????
